import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/Header"
import { ThemeProvider } from "@/app/components/ThemeProvider"
import Footer from "./components/Footer"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Movies World",
	description: "Generated by create ",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className="dark" suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProvider>
					<Header />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
